<?xml version="1.0"?>
<package format="3">
  <name>trac_ik_python</name>
  <version>2.0.0</version>
  <description>The trac_ik_python package contains a python wrapper using SWIG
  for trac_ik_lib</description>
  <maintainer email="aprotyas@u.rochester.edu">Abrar Rahman Protyasha</maintainer>
  <author>Sam Pfeiffer</author>
  <license>BSD</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>ament_cmake_python</buildtool_depend>

  <build_depend>swig</build_depend>
  <build_depend>python3-dev</build_depend>
  <build_depend>trac_ik_lib</build_depend>
  <build_depend>kdl_parser</build_depend>
  <build_depend>urdf</build_depend>
  <build_depend>libnlopt-dev</build_depend>
  <build_depend>rclpy</build_depend>

  <exec_depend>swig</exec_depend>
  <exec_depend>python3-numpy</exec_depend>
  <exec_depend>trac_ik_lib</exec_depend>
  <exec_depend>kdl_parser</exec_depend>
  <exec_depend>urdf</exec_depend>
  <exec_depend>libnlopt-dev</exec_depend>
  <exec_depend>libnlopt0</exec_depend>
  <exec_depend>rclpy</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>

</package>
